#!/bin/bash

echo "=================================="
echo "Local Subdomain Testing Setup"
echo "=================================="
echo ""
echo "Add these to /etc/hosts for local testing:"
echo ""
echo "127.0.0.1 harrychang.local"
echo "127.0.0.1 lab.harrychang.local"
echo ""
echo "To add them automatically (requires sudo):"
echo "sudo sh -c 'echo \"127.0.0.1 harrychang.local\" >> /etc/hosts'"
echo "sudo sh -c 'echo \"127.0.0.1 lab.harrychang.local\" >> /etc/hosts'"
echo ""
echo "Then access:"
echo "http://harrychang.local:3000 (main site)"
echo "http://lab.harrychang.local:3000 (lab site)"
echo ""
